---
- name: To configure the newly created EC2 with terraform
  host: all
  become: true
  become_method: sudo

  tasks:
    -name: Install the nginx in EC2 - amazon linux
     command: yum install nginx -y

