---
- name: To configure the newly created EC2 with terraform
  host: webserver
  become: true
  become_method: sudo

  tasks:
    - name: Install the nginx in EC2 - amazon linux
      yum:
        name: nginx
        state: present
    - name: Start NGiNX
      service:
        name: nginx
        state: started
